# to run this example you will need the following :
""" 
An active enpoint running localAI as a REST service
Example:
curl http://34.148.227.54:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
  "model": "qwen2.5-0.5b-instruct",
  "messages": [{"role": "user", "content": "Recommend a nursery rhyme for a 4 year old girl."}],
  "temperature": 0.3
}'
"""

# sample execution: > 
""" 
python simpleLLM_with_cache.py -h <host> -p <port> [optional -s <password>] [optional -u <username>] 
python3 simpleLLM_with_cache.py -h redis-18000.homelabwin.local -p 18000
python3 simpleLLM_with_cache.py -h redis-10000.re-cluster1.ps-redislabs.org -p 10000
"""

# redis imports: for caching prompts and responses and 
# searching using Vector Similarity for previous prompts 

from redis.commands.search.field import VectorField
from redis.commands.search.query import Query
from redis.commands.search.index_definition import IndexDefinition, IndexType
# import to allow easy HTTP calls:
import requests
# import to allow manipulation of json and jsonpath navigation of response from LLM:
import json, jsonpath_ng.ext as jsonpath
#LLM related imports:
from sentence_transformers import SentenceTransformer
#general imports: 
import time,uuid
### cmdline_utils==General Setup &
# CLI and cache connection functions: ###
from cmdline_utils import *
from datastore_connection_util import *
from prompt_templates import *

# when generating keys to be included in our search index
# as well as the name of our search index we use this string
# to avoid collisions with other data and indexing unnecessary data:
uid_prefix = "ot11"

''' 
The string generated by this function is used as the keyname for 
the Object in Redis that holds the user prompt text and 
points to the cached response.
The actual KeyName is not important (except for its prefix)
As we are using Redis Query Engine and all such objects are being
indexed.  
'''
def string_for_keyname():
    s = str(uuid.uuid4())
    return(uid_prefix+':prompt:'+s)

### LLM / AI Setup ###
# Q: where is the LLM library? A: we are using a hosted 'localAI' server
# https://localai.io/ 
llm_chat_url = "http://localhost:6060/v1/chat/completions"
        
# prep for Search index creation logic 
# - most invocations won't need to create a new index:
create_new_index = True

# this function creates the index in redis and returns its name:
def create_index_in_cache(datastore_connection):
    index_name = 'idx_vss_lclllm_'+uid_prefix
    SCHEMA = [
        VectorField("embedding", "FLAT", {"INITIAL_CAP": 1000, "TYPE": "FLOAT32", "DIM": 768, "DISTANCE_METRIC": "COSINE"}),
    ]
    # Create the index (Index is created in the Redis Database)
    try:
        datastore_connection.ft(index_name).create_index(fields=SCHEMA, definition=IndexDefinition(prefix=[(uid_prefix+":prompt:")], index_type=IndexType.HASH))
    except Exception as e:
        print(repr(e))
    return index_name

# this function executes the VSS search call against Redis
# it accepts a redis index (generated by calling connection)
def vec_search(vindex, query_vector_as_bytes):
    # Dragonfly requires a clean VECTOR_RANGE statement.
    # We yield the distance as 'knn_dist' and sort/limit it manually.
    '''query = (
        Query('@embedding:[VECTOR_RANGE 0.4 $knn_vec]=>{$yield_distance_as: knn_dist}')
        .sort_by('knn_dist')  # Sort from closest to furthest
        .return_fields("response_key", "knn_dist")
        .dialect(2)
    )  '''
    query = (
        Query('@embedding:[VECTOR_RANGE {threshold} $knn_vec]=>{{$yield_distance_as: knn_dist}}'
          .format(threshold=parse_connection_args().get('similarity_threshold', DEFAULTS['similarity_threshold'])))
        .sort_by('knn_dist')
        .return_fields("response_key", "knn_dist")
        .dialect(2)
    )  
    print(f"DEBUG: Executing this vector query:\n {query}\n")

    # Execute the query against Dragonfly
    res = vindex.search(query, query_params={
        'knn_vec': query_vector_as_bytes
    })

    print(f"DEBUG: Search returned {res.total} results.")
    
    # Check if any documents fell within the distance threshold
    if res.total == 0:
        print("No semantic match found within the specified range.")
        return None
        
    # By default, Dragonfly/Redis returns up to 10 items via .limit(0, 10).
    # If you need to strictly cap it at a lower number (like top 5), 
    # you can slice the array here or add `.limit(0, 5)` to the Query object.
    return res.docs

## This function is where we interact with the LLM 
# - providing a prompt that guides the behavior as well as 
# the question posed by the user:
def ask_llm(question):
    # a little prompt engineering is needed to get the answers in a usable format:
    # HERE IS WHERE you could call a different prompt_template function:
    template_=template_base(question) 
    #template_=template_music(question)
    #template_=template_gang(question)
    #template_=template_poet(question)

    #qwen3.5-9b-glm5.1-distill-v1    llm_request_data = {"model": "qwen2.5-1.5b-instruct","response_format": {"type": "json"}, "messages": [{"role": "user", "content": f"{template_}"}], "temperature": 0.
    llm_request_data = {"model": "qwen3.5-9b-glm5.1-distill-v1","response_format": {"type": "json"}, "messages": [{"role": "user", "content": f"{template_}"}], "temperature": 0.25}
    print(f"DEBUG: we are sending this to the LLM:\n {llm_request_data}")
    headers =  {"Content-Type": "application/json"}    
    myResponse = requests.post(llm_chat_url,json=llm_request_data,headers=headers )
    decoded_json = myResponse.content.decode('utf-8')
    json_data = json.loads(decoded_json)
    print(f"\nDEBUG: {json_data.keys()}")    

    # provide a default string for the reply in case LLM fails:
    response_s = "Unknown (Not Answered)"

    # Specify the path to be used within the JSON returned from the LLM: 
    json_query = jsonpath.parse("choices[0].message.content")
    # thought: how could we use jsonpath.parse to extract the count of tokens used?

    ## extract the value located at the path we selected in our json_query
    for match in json_query.find(json_data):
        response_s=match.value

    return response_s

if __name__ == "__main__":
    datastore_connection = connect_to_datastore()
    # initialize index in Redis (will not break if we attempt again)
    index_name = create_index_in_cache(datastore_connection)

    # UI loop: (if user responds with "END" or "end" - program ends)
    while True:

        ## useful examples:
        # https://blog.baeke.info/2023/03/21/storing-and-querying-for-embeddings-with-redis/ 
        # https://github.com/RediSearch/RediSearch/blob/master/docs/docs/vecsim-range_queries_examples.ipynb
        sentences = [display_menu()]
        user_input = sentences
        model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
        # create the numpy array encoding representation of the sentences/prompt:
        embeddings = model.encode(sentences)
        # convert the embedding numpy array to bytes for use in Redis Hash:
        #embedding_vector_as_bytes = embeddings.tobytes() (below might help)
        embedding_vector_as_bytes = embeddings.astype('float32').tobytes()

        # pass the user text/prompt to the LLM Chain and print out the response: 
        # also, check for a suitable cached response
        if user_input:
            # we are interested in seeing how long it takes to use Vectors: 
            start_time=time.perf_counter()

            # assign the details of the hash value to be stored: 
            prompt_hash = {
                "prompt_used": sentences[0],
                "embedding": embedding_vector_as_bytes,
                "response_key": "__empty__"
            }

            # Before we search for a semantically similar prompt,
            # we need to make sure we store the hash in Redis with 
            # this latest prompt:
            """ Uncomment the following line to enable Semantic caching """
            datastore_connection.hset(name=string_for_keyname(), mapping=prompt_hash)

            # now we can search for semantically similar prompt(s)
            results = vec_search(datastore_connection.ft(index_name),embedding_vector_as_bytes)
            # only write the response to prompt hashes in redis with response_key=""
            # due to the sortby this should always at least be the one at zero index
            # we expect at most 10 docs (KNN 10 is specified in query)
            # they are in asc distance order - smaller the distance the better
            found_useful_result = False
            llm_response = ""
            for next_result in results:
                if not next_result.response_key == "__empty__":
                    # ensure that we only reuse a response that is suitable
                    # cached responses are stored as strings in redis 
                    # and the keyname for the relevant string is stored in the 
                    # response attribute of the prompt Hash object in Redis.
                    # This decouples the storage of the answer allowing for more reuse
                    # answers stored this way can easily be edited and all similar prompts will 
                    # point to this now, updated response|answer
                    print(f'\nFound a match! -->\n {next_result}\n')
                    found_useful_result = True
                    # llm_reponse_cache_key should point to a string in redis:
                    llm_response_cache_key=next_result.response_key
                    print(f'keyname of cached response: {llm_response_cache_key}')
                    llm_response=datastore_connection.get(llm_response_cache_key)
                if found_useful_result: 
                    # write the nearby result as the response to this prompt in redis
                    # in this way, multiple prompts may share the same result
                    datastore_connection.hset(results[0].id,'response_key',llm_response_cache_key)
                    break
            # we have exhausted all the potential matches:
            if not found_useful_result:
                print('\n No suitable response has been cached.  Generating new Response...\n')
                # create a new LLM-generated result as the answer:            
                llm_response = ask_llm(user_input) 
                x = datastore_connection.incr(f'{uid_prefix}:prompt:responsekeycounter')
                # store the full response in a string in redis 
                datastore_connection.set(f'{uid_prefix}:prompt:response:{x}',llm_response)
                # write the cached response keyname to the response attribute in redis:
                # due to sorting of the results by KNN distance ASC the first result should be our target:
                if (results):
                    datastore_connection.hset(results[0].id,'response_key',(f'{uid_prefix}:prompt:response:{x}'))            
            
            # output whatever the result is to the User Interface:
            print(f'{spacer}\n{llm_response}{spacer}\n')
            uparrows = " ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ \n"
            print(f'\t{uparrows}\tElapsed Time to respond to user prompt was: {(time.perf_counter()-start_time)*1} seconds\n')

